# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9afadc4e1df0e8e11ff6bb1cf8bc87c4544934a2dd418dd0709efcd15c41fb1d6aecfa6584a2ae970232235244c3e2353d03beb83b0884134190ad6578b84d60

test:
  secret_key_base: aeaa42b84a2635dc9c4dc595aaa28b4e87ad72bb292cd6246ebca1d7309c109c43d3e5fd20c3a0c685901520648018c216799183101fc602030c1604895df144

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
